CREATE TABLE ChatMessages (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    SenderId NVARCHAR(100) NOT NULL,
    ReceiverId NVARCHAR(100) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    Timestamp DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
